### ===========================================
###           1. LOGIN (Ejecutar este primero)
### ===========================================
# @name login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "12345"
}

> {%
    client.global.set("authToken", response.body.jwt);
%}


### ===========================================
###           2. GESTIÓN DE PLATOS
### ===========================================
# Separador para que IntelliJ entienda que es una nueva petición
###

### Crear un nuevo plato (POST)
POST http://localhost:8080/api/dishes
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Pizza",
  "description": "Pescado fresco marinado en jugo de limón.",
  "price": 65.00,
  "active": true,
  "categoryId": 2
}


### ===========================================
###           3. GESTIÓN DEL MENÚ DIARIO
### ===========================================
###

### Crear un menú diario (POST)
POST http://localhost:8080/api/menus
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "menuDate": "2025-08-25",
  "dishes": [
    {
      "dishId": 1,
      "initialStock": 30
    },
    {
      "dishId": 6,
      "initialStock": 25
    },
    {
      "dishId": 3,
      "initialStock": 25
    },
    {
      "dishId": 2,
      "initialStock": 25
    }
  ]
}


### ===========================================
###           4. GESTIÓN DE PEDIDOS
### ===========================================
###

### Crear un nuevo pedido (POST)
POST http://localhost:8080/api/orders
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "orderType": "MENU_COMPLETO",
  "userId": 1,
  "items": [
    {
      "dailyMenuDishId": 1
    },
    {
      "dailyMenuDishId": 2
    }
  ]
}