### Realiz login para obt un tokn JWT
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "12345"
}

### GESTIÓN DE PLATOS

### Crear un nuevo plato (POST)
# Nota: El categoryId debe corresponder a un ID existente en tu tabla dish_categories.
# 1=Sopas, 2=Entradas, 3=Segundos (generalmente).

POST http://localhost:8080/api/dishes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc1NDg1NDczNCwiZXhwIjoxNzU0ODkwNzM0fQ.soKZC9wRXY1rsXa0CYcstyKQqwIdIsrGLpTyhgevZGU

{
  "name": "Lomo Saltado",
  "description": "Trozos jugosos de lomo fino salteados con cebolla, tomate y ají amarillo.",
  "active": true,
  "categoryId": 3
}
